[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'MarcWeber/vim-addon-mw-utils'

[[plugins]]
repo = 'tomtom/tlib_vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'AkioYokoyama/vim-surround'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'vim-scripts/smarty-syntax'
on_ft = 'html'

[[plugins]]
repo = 'joonty/vdebug'

[[plugins]]
repo = 'osyo-manga/shabadou.vim'

[[plugins]]
repo = 'kana/vim-submode'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
